### ISSUE TITLE
Use Firebase Hosting

### ISSUE THREAD

**Issue by WillowHQ** [WillowHQ/retro_v1#4]
- Set up Firebase hosting so the app is being served there. Google Firebase Hosting to get started. 
- Submit a PR with the required changes.

**Comment by abirhalwa** [comment]
When trying to set up the Firebase Hosting through the cmd, it says that the firebase hosting is already connected to a firebase project.
When trying to use Firebase init, it says that I don't have authorization to access the database!

**Comment by WillowHQ** [comment]
Right, you need to be added to the firebase project. Thanks we will set that up next week !

**Comment by CoachThomLamb** [comment]
Firebase is being used for database, auth, and hosting.
