### ISSUE TITLE
Create a new default Board

### ISSUE THREAD

**Issue by WillowHQ** [WillowHQ/retro_v1#6]
- An Admin User can create a new Board that has the following configuation. 
- Four Lanes: ["What went well". "What needs improvement", "Discussion", "Action"]
- The following Lanes allow other users to add Cards to them. ["What went well", "What needs improvement"]. Add an issue to set this up. 
- The Discussion Lane receives Cards from the Previous Two, and these Cards can only be moved to it by the Owner of the Board. Add an issue to link to to set this up. 
- The Action Lane only accepts Cards when a button is pressed on a Decision Card to generate an Action. TODO: Add an issue to set this up.

**Comment by CoachThomLamb** [comment]
Board has cards, there is no logic about how the cards can move between the lanes yet. Save that for later.
