### ISSUE TITLE
A User can Create a Card on ["What went well", "What needs improvement"]

### ISSUE THREAD

**Issue by WillowHQ** [WillowHQ/retro_v1#7]
- Any user can click on Add a Card in the Lanes "what went well", or "what needs improvement" and create a card. 
- The card has a description. 
- It has a link to the Lane it is in. 
- It has a code to know what user created it. This is hidden from everyone (How to do this ?). 
- The creator of the Card can edit it before they submit it, after that it can't be edited by anyone. It can be deleted. 
- Don't need votes for MVP ?

**Comment by CoachThomLamb** [comment]
Cards can be created by anyone that can access the board. Not storing user data at that level in any way right now.
